### PR TITLE
made some fixes in deployment

### PR DESCRIPTION
**Pull request by infosec-alchemist**
- The task-prep-remote-hosts.yml playbook will install packages in sudo
- The deployment will create the volumes rather than error when they aren't there
- Added Ingest to the the Build
- Running "ansible-playbook task-approve-recent-user.yml" will let you approve any user on all your deployed hosts.
- task-prep-remote-hosts.yml playbook will create self signed certs on all the deployed hosts

### CODE REVIEW

**Comment by webiator** [comment]
While running task-prep-remote-hosts playbook:
```
TASK [common : Create certs volume] ****************************************************************************************************************************
fatal: [dev]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))"}
```

**Review by ghost — CHANGES_REQUESTED** [review]
task-prep-remote-hosts playbook needs to create the network (and probably more) in order to create the server certs. Fresh EC2 instance.

**Comment by infosec-alchemist** [comment]
Okay, added the creation of the docker network

**Comment by webiator** [comment]
Still can't do prod-uac deployments. private-config volume is overwritten every time I deploy, and it's writing the URLs as https://ec2.internal, instead of using the IP or domain I provide in the host_vars file.

Still can't do dev deployments. Keeps trying to cd to ../../unfetter-store/unfetter-discover-processor, rather than using the directory I provide in the host_vars file. The git repositories are not being cloned into that directory any longer, either.

**Review by ghost — APPROVED** [review]

**Comment by webiator** [comment]
To make prod-uac work:
- Had to edit the private-config.json file inside the unfetter-discover-api container. Changed the `ec2.internal` URLs to the actual domain name of the instance.
- Ran `docker stop unfetter-discover-api unfetter-discover-gateway`.
- Ran `docker container restart unfetter-discover-api unfetter-discover-gateway`.
- Waited for both to finish restarting. Reloaded UI and logged in. Registration page loaded.

From there I registered, then ran the approve-user playbook without issues. Logged back into the UI, and got the user home page, dropdown had Admin page, admin page loaded without issue.

**Pull request merged**
