### PR TITLE
Issue 1449

### PR DESCRIPTION
**Pull request by infosec-alchemist**
Can now configure and deploy unfetter to a remote host.
- No code to be checked out at remote host
- Fully deploy docker to centos hosts
- Support remote backups

Code to start EC2 instances that have the proper tags

Tested with host_vars file for deployment specific infrastructure

To test:
Build EC2 instances based on Centos machines.
- Create tag called "deployment-group" with a value of "unfetter"
- Create a tag called "unfetter-deployed" with the ansible hostname
Ensure SSH user access from orchestration box to host
Install Python to remote host to support Ansible
Build host_var files for every desired deployed configuration
Change the [deployed] group in hosts.ini

`ansible-playbook task-prep-remote-host.yml`
`ansible-playbook deploy.yml`

This will build Unfetter on that remote host.

### CODE REVIEW

**Comment by webiator** [comment]
Assuming I followed the instructions correctly, I got the following error calling the deploy playbook:
```
TASK [set_fact] ************************************************************************************************************************************************
fatal: [my-ec2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'use_uac' is undefined\n\nThe error appears to have been in '/Users/carltonanderson/work/unfetter/unfetter-discover/ansible/discover-tasks.yml': line 24, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - set_fact:\n    ^ here\n"}
```

My host_vars file reads:
```
---
remote_tmp: "~"
ansible_connection: "ssh"
backup_directory: "{{ remote_tmp }}/unfetter"
ansible_user: "ec2-user"
ansible_ssh_private_key_file: "/Users/carltonanderson/Downloads/csanderson.pem"
ansible_host: "54.174.90.252"
api_domain: "ec2-54-174-90-252.compute-1.amazonaws.com"
ui_domain: "ec2-54-174-90-252.compute-1.amazonaws.com"
```

Will set `use_uac` variable in the host_vars file, and retry.

**Comment by webiator** [comment]
Same problem, with: `build_action`

Then: `use_unfetter_ui`

Then: `prepath`

**Review by ghost — CHANGES_REQUESTED** [review]
At this point I stopped. I figure I either haven't set something correctly, missed a step, something isn't mentioned in the PR steps, or there is something incomplete in the PR.

**Comment by webiator** [comment]
I switched out hosts.ini in case that was the problem (although I have no idea how it would then know to deploy remotely):
```
[deployed]
prod-uac
#my-ec2
```
But it then complained about the latest_production_tag being missing. I assume this is a reference to the previous PR being needed before I can run normal ansible deployments with this release, so if this is not an issue, please ignore.

**Review by ghost — APPROVED** [review]

**Pull request merged**
