### PR TITLE
Issue 1321

### PR DESCRIPTION
**Pull request by infosec-alchemist**
Run the playbook build-prod.yml will build all the docker images, including the legacy and demo versions of gateway for pushing to docker hub.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Got this error:
```
TASK [gateway : Build new template] ****************************************************************************************************************************
fatal: [build]: FAILED! => {"changed": false, "checksum": "53c74d5bbe82478eda418d1bb1dfec5271673eab", "msg": "Destination directory ../../unfetter/ansible/roles/gateway/files/conf.d does not exist"}
```

Also saw this warning (doubt it's a big deal, probably a cleanup thing):
```
TASK [include_role : gateway] **********************************************************************************************************************************
 [WARNING]: Ignoring invalid attribute: remote_src
```

**Comment by webiator** [comment]
Okay, I think the error above was effectively resolved when I ran a deploy playbook, and it filled in that missing directory. So it's getting past that now, and gets to where it is trying to build the gateway, when it gives these errors:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/Dockerfile.demo'
failed: [build] (item=demo) => {"changed": false, "item": "demo", "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3xzhYU/ansible_module_docker_image.py\", line 605, in <module>\n    main()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3xzhYU/ansible_module_docker_image.py\", line 600, in main\n    ImageManager(client, results)\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3xzhYU/ansible_module_docker_image.py\", line 293, in __init__\n    self.present()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3xzhYU/ansible_module_docker_image.py\", line 321, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3xzhYU/ansible_module_docker_image.py\", line 523, in build_image\n    for line in self.client.build(**params):\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 152, in build\n    dockerfile = process_dockerfile(dockerfile, path)\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 338, in process_dockerfile\n    with open(abs_dockerfile, 'r') as df:\nIOError: [Errno 2] No such file or directory: '/Dockerfile.demo'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/Dockerfile.legacy.demo'
failed: [build] (item=legacy.demo) => {"changed": false, "item": "legacy.demo", "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3jDf8w/ansible_module_docker_image.py\", line 605, in <module>\n    main()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3jDf8w/ansible_module_docker_image.py\", line 600, in main\n    ImageManager(client, results)\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3jDf8w/ansible_module_docker_image.py\", line 293, in __init__\n    self.present()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3jDf8w/ansible_module_docker_image.py\", line 321, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_3jDf8w/ansible_module_docker_image.py\", line 523, in build_image\n    for line in self.client.build(**params):\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 152, in build\n    dockerfile = process_dockerfile(dockerfile, path)\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 338, in process_dockerfile\n    with open(abs_dockerfile, 'r') as df:\nIOError: [Errno 2] No such file or directory: '/Dockerfile.legacy.demo'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/Dockerfile.legacy.uac'
failed: [build] (item=legacy.uac) => {"changed": false, "item": "legacy.uac", "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_287n2Q/ansible_module_docker_image.py\", line 605, in <module>\n    main()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_287n2Q/ansible_module_docker_image.py\", line 600, in main\n    ImageManager(client, results)\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_287n2Q/ansible_module_docker_image.py\", line 293, in __init__\n    self.present()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_287n2Q/ansible_module_docker_image.py\", line 321, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_287n2Q/ansible_module_docker_image.py\", line 523, in build_image\n    for line in self.client.build(**params):\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 152, in build\n    dockerfile = process_dockerfile(dockerfile, path)\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 338, in process_dockerfile\n    with open(abs_dockerfile, 'r') as df:\nIOError: [Errno 2] No such file or directory: '/Dockerfile.legacy.uac'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/Dockerfile.uac'
failed: [build] (item=uac) => {"changed": false, "item": "uac", "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_friarF/ansible_module_docker_image.py\", line 605, in <module>\n    main()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_friarF/ansible_module_docker_image.py\", line 600, in main\n    ImageManager(client, results)\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_friarF/ansible_module_docker_image.py\", line 293, in __init__\n    self.present()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_friarF/ansible_module_docker_image.py\", line 321, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/xd/vh571s492llf6c0x9p1r1ks80000gr/T/ansible_friarF/ansible_module_docker_image.py\", line 523, in build_image\n    for line in self.client.build(**params):\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 152, in build\n    dockerfile = process_dockerfile(dockerfile, path)\n  File \"/Library/Python/2.7/site-packages/docker/api/build.py\", line 338, in process_dockerfile\n    with open(abs_dockerfile, 'r') as df:\nIOError: [Errno 2] No such file or directory: '/Dockerfile.uac'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by webiator** [comment]
If I take off the leading slash on the file names, the build goes all the way through. I can check in that change, if you like, and I will merge the PR in.

**Comment by infosec-alchemist** [comment]
I didn't have any trouble with the /, but it shouldn't be there.  I wonder why it caused you trouble.  I'm guessing there was something else in the variables that was different.

I updated task-build-release.yml to remove the /

**Pull request merged**
